import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const supabase = createClient(window.LIFE_SUPABASE_URL, window.LIFE_SUPABASE_KEY);

const colors=["#ff6b6b","#4dabf7","#69db7c","#ffd43b","#b197fc","#ff922b"], avatars=["🚗","🚙","🚕","🚐","🏎️","🚘"];
const collegeCareers=[["Doctor",130000,45000],["Lawyer",115000,40000],["Engineer",100000,35000],["Scientist",95000,32000],["Professor",85000,28000],["Pilot",110000,38000]];
const fastCareers=[["Chef",60000,18000],["Artist",55000,16000],["Mechanic",65000,19000],["Influencer",70000,21000],["Entrepreneur",80000,24000],["Designer",72000,22000]];
const houses=[["Cozy Cottage",140000,180000,"🏡"],["City Condo",220000,260000,"🏢"],["Family Home",360000,430000,"🏠"],["Beach House",520000,650000,"🏖️"],["Dream Mansion",800000,1000000,"🏰"]];
const actions=[["Win a TV game show",80000,0,0],["Start a charity fundraiser",-20000,1,0],["Car breaks down",-30000,0,0],["Sell an app idea",120000,0,0],["Vacation around the world",-40000,1,0],["Lawsuit settlement",60000,0,0],["Home repairs",-25000,0,0],["Help a friend move",0,1,0],["Stock market jump",100000,0,0],["Go back to school",-50000,0,20000],["Win community award",30000,1,0],["Lose your wallet",-15000,0,0]];
const path=[
{x:40,y:620,type:"start",label:"START"},{x:150,y:620,type:"college",label:"COLLEGE / CAREER"},{x:260,y:620,type:"action",label:"ACTION"},{x:370,y:620,type:"payday",label:"PAYDAY"},{x:480,y:620,type:"career",label:"CAREER"},{x:590,y:620,type:"life",label:"LIFE TILE"},{x:700,y:620,type:"house",label:"HOUSE"},{x:810,y:620,type:"payday",label:"PAYDAY"},{x:810,y:500,type:"family",label:"MARRIAGE"},{x:700,y:500,type:"action",label:"ACTION"},{x:590,y:500,type:"tax",label:"TAXES"},{x:480,y:500,type:"payday",label:"PAYDAY"},{x:370,y:500,type:"family",label:"BABY"},{x:260,y:500,type:"house",label:"HOUSE"},{x:150,y:500,type:"action",label:"ACTION"},{x:40,y:500,type:"life",label:"LIFE TILE"},{x:40,y:380,type:"payday",label:"PAYDAY"},{x:150,y:380,type:"career",label:"CAREER CHANGE"},{x:260,y:380,type:"family",label:"TWINS?"},{x:370,y:380,type:"action",label:"ACTION"},{x:480,y:380,type:"payday",label:"PAYDAY"},{x:590,y:380,type:"house",label:"HOUSE"},{x:700,y:380,type:"tax",label:"TAXES"},{x:810,y:380,type:"life",label:"LIFE TILE"},{x:810,y:260,type:"action",label:"ACTION"},{x:700,y:260,type:"payday",label:"PAYDAY"},{x:590,y:260,type:"family",label:"ADOPT PET"},{x:480,y:260,type:"career",label:"RAISE"},{x:370,y:260,type:"action",label:"ACTION"},{x:260,y:260,type:"payday",label:"PAYDAY"},{x:150,y:260,type:"life",label:"LIFE TILE"},{x:40,y:260,type:"house",label:"HOUSE"},{x:40,y:140,type:"payday",label:"PAYDAY"},{x:150,y:140,type:"action",label:"ACTION"},{x:260,y:140,type:"tax",label:"TAXES"},{x:370,y:140,type:"family",label:"FAMILY"},{x:480,y:140,type:"payday",label:"PAYDAY"},{x:590,y:140,type:"life",label:"LIFE TILE"},{x:700,y:140,type:"action",label:"ACTION"},{x:810,y:140,type:"retire",label:"RETIRE"}];

let state=fresh(),mode="solo",gameCode=null,myId=null,isHost=false,channel=null,poll=null,tab="career";
const $=id=>document.getElementById(id);
["solo","local","host","join"].forEach(x=>$(x+"Btn").onclick=()=>x==="host"?hostOnline():openLobby(x));
$("backBtn").onclick=showHome;$("lobbyAction").onclick=lobbyAction;$("startBtn").onclick=startGame;$("copyBtn").onclick=()=>navigator.clipboard?.writeText(gameCode||"");$("resetBtn").onclick=()=>location.reload();
$("spinBtn").onclick=spin;$("pathBtn").onclick=choosePath;$("careerBtn").onclick=drawCareer;$("actionBtn").onclick=()=>drawAction(true);$("houseBtn").onclick=houseShowroom;$("loanBtn").onclick=repayLoan;$("retireBtn").onclick=retire;$("endBtn").onclick=()=>endTurn();
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTabs();});

function fresh(){return{status:"lobby",players:[],current:0,spin:0,log:[],winnerId:null,lastCard:null};}
function openLobby(kind){mode=kind==="join"?"online":kind;isHost=kind!=="join"&&kind!=="online";gameCode=null;myId=null;state=fresh();$("homeScreen").classList.add("hidden");$("gameScreen").classList.add("hidden");$("lobbyScreen").classList.remove("hidden");$("codeBox").classList.add("hidden");$("joinCode").classList.toggle("hidden",kind!=="join");$("startBtn").classList.add("hidden");$("playersList").innerHTML="";$("statusText").textContent="";$("lobbyAction").classList.remove("hidden");$("playerName").value="";$("lobbyTitle").textContent=kind==="solo"?"Single Player":kind==="local"?"Pass-and-Play Lobby":"Join Online Game";$("lobbyHelp").textContent=kind==="solo"?"Enter your name. Bots join automatically.":kind==="local"?"Add 2–6 players.":"Enter the game code and your name.";}
function showHome(){stopSync();$("homeScreen").classList.remove("hidden");$("lobbyScreen").classList.add("hidden");$("gameScreen").classList.add("hidden");}
async function hostOnline(){mode="online";isHost=true;myId=id();gameCode=code();state=fresh();let {error}=await supabase.from("life_games").insert({code:gameCode,state});if(error)return alert(error.message+"\\nRun life-v4-supabase-setup.sql first.");subscribe(gameCode);$("homeScreen").classList.add("hidden");$("lobbyScreen").classList.remove("hidden");$("lobbyTitle").textContent="Host Online Game";$("lobbyHelp").textContent="Share the code. Add yourself, then start."; $("codeBox").classList.remove("hidden");$("codeText").textContent=gameCode;$("joinCode").classList.add("hidden");$("startBtn").classList.remove("hidden");}
async function lobbyAction(){const name=$("playerName").value.trim();if(!name)return alert("Enter a player name.");if(mode==="solo"){state=fresh();addPlayer(name,"human");["Bot Sunny","Bot Sky","Bot Rose"].forEach(n=>addPlayer(n,"bot"));myId=state.players[0].id;return startGame()}if(mode==="local"){if(state.players.length>=6)return alert("Max 6 players.");addPlayer(name,"human");$("playerName").value="";renderLobby();$("startBtn").classList.toggle("hidden",state.players.length<2);return}if(mode==="online"&&!isHost){const c=$("joinCode").value.trim().toUpperCase();let {data,error}=await supabase.from("life_games").select("state").eq("code",c).single();if(error||!data)return alert("Game not found.");state=data.state;gameCode=c;myId=id();if(state.status!=="lobby")return alert("Game already started.");state.players.push(makePlayer(name,"human",state.players.length,myId));await save();subscribe(c);$("codeBox").classList.remove("hidden");$("codeText").textContent=c;$("joinCode").classList.add("hidden");$("lobbyAction").classList.add("hidden");$("statusText").textContent="Joined. Waiting for host.";renderLobby();return}if(mode==="online"&&isHost){if(state.players.some(p=>p.id===myId))return;state.players.push(makePlayer(name,"human",state.players.length,myId));await save();$("playerName").value="";renderLobby();}}
function addPlayer(n,k){state.players.push(makePlayer(n,k,state.players.length));}
function makePlayer(name,kind,i,forced){return{id:forced||id(),name,kind,color:colors[i%colors.length],avatar:avatars[i%avatars.length],pos:0,cash:200000,loans:0,career:null,salary:0,tax:0,house:null,married:false,kids:0,pets:0,lifeTiles:[],pathChosen:false,retired:false,moved:false};}
async function startGame(){if(state.players.length<2)return alert("Add at least 2 players.");state.status="playing";state.log=["Welcome to Life Deluxe V4! First choose College or Career."];await changed();enter();}
function enter(){$("homeScreen").classList.add("hidden");$("lobbyScreen").classList.add("hidden");$("gameScreen").classList.remove("hidden");render();setTimeout(botTurn,700);}
function renderLobby(){$("playersList").innerHTML=state.players.map((p,i)=>`<span class="chip"><span class="token" style="background:${p.color}">${esc(p.avatar)}</span>${i+1}. ${esc(p.name)}${p.kind==="bot"?" / Bot":""}</span>`).join("");}
function render(){if(state.status==="lobby")return renderLobby();if(state.status==="playing"||state.status==="ended"){if($("gameScreen").classList.contains("hidden"))enter();renderLeft();renderBoard();renderCenter();renderTabs();renderCard();}}
function renderLeft(){let p=cur(),me=viewer()||p;$("currentPlayerTitle").textContent=p?.name||"—";$("activePlayerCard").innerHTML=playerCardHTML(me,true);$("playerStrip").innerHTML=state.players.map((x,i)=>`<div class="miniPlayer ${i===state.current?"current":""}"><span class="token" style="background:${x.color}">${x.avatar}</span> <strong>${esc(x.name)}</strong><div class="tiny">${money(net(x))}</div></div>`).join("");$("eventFeed").innerHTML=[...state.log].reverse().slice(0,5).map(x=>`<div class="feedItem">${esc(x)}</div>`).join("");}
function playerCardHTML(p,big=false){return `<div class="playerHead"><span class="avatarBig" style="background:${p.color}">${p.avatar}</span><div><h2>${esc(p.name)} ${p.retired?"🏁":""}</h2><p class="tiny">${esc(p.career||"No career")} • ${esc(p.house?.name||"No house")}</p></div></div><div class="statGrid"><div class="stat">Cash<br><span class="money">${money(p.cash)}</span></div><div class="stat">Loans<br><span class="debt">${money(p.loans)}</span></div><div class="stat">Family<br>${p.married?"💍":""} 👶${p.kids} 🐾${p.pets}</div><div class="stat">Life Tiles<br>⭐ ${p.lifeTiles.length}</div><div class="stat">Salary<br>${money(p.salary)}</div><div class="stat">Net<br><span class="money">${money(net(p))}</span></div></div>`;}
function renderBoard(){let b=$("board");b.innerHTML="";for(let i=0;i<path.length-1;i++){let a=path[i],n=path[i+1],dx=n.x-a.x,dy=n.y-a.y,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;b.insertAdjacentHTML("beforeend",`<div class="road" style="left:${a.x+46}px;top:${a.y+32}px;width:${len}px;transform:rotate(${ang}deg)"></div>`)}path.forEach((t,i)=>{let here=state.players.filter(p=>p.pos===i&&!p.retired);let tokens=here.length?`<div class="tokens">${here.map(p=>`<span class="token" style="background:${p.color}" title="${esc(p.name)}">${p.avatar}</span>`).join("")}</div>`:"";b.insertAdjacentHTML("beforeend",`<div class="tile ${t.type} ${i===cur()?.pos?"current":""}" style="left:${t.x}px;top:${t.y}px"><strong>${i}</strong><br>${esc(t.label)}${tokens}</div>`)});$("retiredTokens").innerHTML=state.players.filter(p=>p.retired).map(p=>`<span class="token" style="background:${p.color}" title="${esc(p.name)}">${p.avatar}</span>`).join("");}
function renderCenter(){let p=cur();$("turnLine").innerHTML=state.status==="ended"?"Game over":`Current turn: <strong>${esc(p?.name||"—")}</strong>`;$("turnBadge").textContent=state.status==="ended"?"Game Over":isMyTurn()?"Your Turn":"Waiting";$("spinnerValue").textContent=state.spin||"?";let mine=isMyTurn();$("spinBtn").disabled=!mine||!p?.pathChosen||p.moved||p.retired||state.status!=="playing";$("pathBtn").disabled=!mine||p?.pathChosen||p?.retired;$("careerBtn").disabled=!mine||!p?.pathChosen||p?.retired;$("actionBtn").disabled=!mine||p?.retired;$("houseBtn").disabled=!mine||p?.retired;$("loanBtn").disabled=!mine||p?.loans<=0;$("retireBtn").disabled=!mine||p?.pos<path.length-1||p?.retired;$("endBtn").disabled=!mine||state.status!=="playing";}
function renderTabs(){let p=viewer()||cur();if(!p)return;let html="";if(tab==="career")html=`<div class="infoCard career"><h3>💼 ${esc(p.career||"No career")}</h3><p>Salary: ${money(p.salary)}<br>Tax: ${money(p.tax)}</p></div><p class="tiny">Use CAREER to draw/change career.</p>`;if(tab==="house")html=`<div class="infoCard house"><h3>${p.house?.icon||"🏠"} ${esc(p.house?.name||"No house")}</h3><p>${p.house?`Bought: ${money(p.house.price)}<br>Sell: ${money(p.house.sell)}`:"Open HOUSE to buy one."}</p></div>`;if(tab==="life")html=`<h3>⭐ Life Tiles</h3>${(p.lifeTiles.length?p.lifeTiles:["No Life Tiles yet"]).slice(-8).map(x=>`<div class="infoCard life">${esc(x)}</div>`).join("")}`;if(tab==="results")html=[...state.players].sort((a,b)=>net(b)-net(a)).map((x,i)=>`<div class="infoCard"><strong>${i+1}. ${x.avatar} ${esc(x.name)}</strong><br>${money(net(x))}</div>`).join("");$("tabContent").innerHTML=html;}
function renderCard(){let c=state.lastCard;$("activeCard").classList.toggle("flipped",!!c?.flip);document.querySelector(".cardFront").innerHTML=c?`<p class="label">${esc(c.type)}</p><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p>`:`<p class="label">Current Card</p><h3>No card yet</h3>`;}
async function choosePath(){let p=cur();let ch=await options("Choose Path",[{v:"college",t:"🎓 College",d:"Borrow $100k, better career"},{v:"career",t:"💼 Career",d:"Start earning now"}]);if(!ch)return;if(ch==="college"){p.loans+=100000;p.cash+=40000;careerFor(p,true);log(`${p.name} went to College and became ${p.career}.`)}else{careerFor(p,false);log(`${p.name} started a Career as ${p.career}.`)}p.pathChosen=true;await changed();}
async function drawCareer(){let p=cur();careerFor(p,p.loans>0);card("Career Card",p.career,`Salary ${money(p.salary)} • Tax ${money(p.tax)}`);log(`${p.name} drew a career card: ${p.career}.`);await changed();}
function careerFor(p,college){let c=pick(college?collegeCareers:fastCareers);p.career=c[0];p.salary=c[1];p.tax=c[2];}
async function spin(){let p=cur(),s=1+Math.floor(Math.random()*10);state.spin=s;$("spinner").style.transform=`rotate(${s*360+Math.random()*90}deg)`;let old=p.pos;p.pos=Math.min(path.length-1,p.pos+s);p.moved=true;log(`${p.name} spun ${s} and moved from ${old} to ${p.pos}.`);resolve(p,path[p.pos]);checkEnd();await changed();}
function resolve(p,t){if(t.type==="payday"){gain(p,p.salary);log(`PAYDAY! ${p.name} collected ${money(p.salary)}.`)}if(t.type==="tax"){lose(p,p.tax);log(`${p.name} paid taxes: ${money(p.tax)}.`)}if(t.type==="career"){p.salary+=20000;gain(p,30000);log(`${p.name} got a career upgrade.`)}if(t.type==="action")drawAction(false);if(t.type==="life"){p.lifeTiles.push("Milestone Memory");gain(p,20000);log(`${p.name} collected a Life Tile.`)}if(t.type==="family")family(p,t.label);if(t.type==="house")log(`${p.name} landed on HOUSE. Open the House panel.`);if(t.type==="retire")log(`${p.name} reached retirement.`)}
function family(p,label){if(label==="ADOPT PET"){p.pets++;p.lifeTiles.push("Adopted a Pet");log(`${p.name} adopted a pet.`);return}if(!p.married){p.married=true;lose(p,25000);p.lifeTiles.push("Got Married");log(`${p.name} got married.`)}else{let k=label==="TWINS?"||Math.random()>.75?2:1;p.kids+=k;lose(p,k*15000);for(let i=0;i<k;i++)p.lifeTiles.push("New Baby");log(`${p.name} welcomed ${k} child${k>1?"ren":""}.`)}}
async function drawAction(saveNow=true){let p=cur(),a=pick(actions);gain(p,a[1]||0);if(a[2])p.lifeTiles.push(a[0]);if(a[3])p.salary+=a[3];card("Action Card",a[0],`${a[1]?money(a[1]):""}${a[2]?" • Gain Life Tile":""}${a[3]?" • Raise "+money(a[3]):""}`);log(`${p.name}: ${a[0]}.`);if(saveNow)await changed();}
async function houseShowroom(){let p=cur();let ch=await options("House Showroom",houses.map((h,i)=>({v:String(i),t:`${h[3]} ${h[0]}`,d:`Price ${money(h[1])} • Sell ${money(h[2])}`})));if(ch===null)return;let h=houses[Number(ch)];p.cash-=h[1];p.house={name:h[0],price:h[1],sell:h[2],icon:h[3]};card("House Card",h[0],`Price ${money(h[1])} • Sell value ${money(h[2])}`);log(`${p.name} bought ${h[0]}.`);toast("-"+money(h[1]),"loss");await changed();}
async function repayLoan(){let p=cur(),amt=Math.min(20000,p.loans);p.loans-=amt;lose(p,amt);log(`${p.name} repaid ${money(amt)} in loans.`);await changed();}
async function retire(){let p=cur();p.retired=true;if(p.house){gain(p,p.house.sell);log(`${p.name} sold ${p.house.name} at retirement.`);p.house=null}let tileCash=p.lifeTiles.length*50000;gain(p,tileCash);log(`${p.name} retired and cashed Life Tiles for ${money(tileCash)}.`);checkEnd();await changed();if(state.status!=="ended")endTurn(true);}
async function endTurn(force=false){if(!force&&!isMyTurn())return;cur().moved=false;state.spin=0;if(state.players.every(p=>p.retired)){checkEnd();await changed();return}do{state.current=(state.current+1)%state.players.length}while(cur().retired);log(`It is now ${cur().name}'s turn.`);await changed();setTimeout(botTurn,700);}
async function botTurn(){if(mode!=="solo"||cur()?.kind!=="bot"||state.status!=="playing")return;setTimeout(async()=>{let p=cur();if(!p.pathChosen){careerFor(p,Math.random()>.5);p.pathChosen=true;log(`${p.name} became ${p.career}.`)}else if(p.pos>=path.length-1){await retire();return}else{let s=1+Math.floor(Math.random()*10);state.spin=s;p.pos=Math.min(path.length-1,p.pos+s);p.moved=true;log(`${p.name} spun ${s}.`);resolve(p,path[p.pos]);}checkEnd();await changed();if(state.status!=="ended")endTurn(true)},900);}
function checkEnd(){if(state.players.every(p=>p.retired)){state.status="ended";let w=[...state.players].sort((a,b)=>net(b)-net(a))[0];state.winnerId=w.id;log(`${w.name} wins with ${money(net(w))}!`);tab="results";document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab==="results"));}}
function gain(p,n){p.cash+=n;if(n>0)toast("+"+money(n),"gain");if(n<0)toast("-"+money(Math.abs(n)),"loss")}function lose(p,n){p.cash-=n;toast("-"+money(n),"loss")}function card(type,title,text){state.lastCard={type,title,text,flip:!state.lastCard?.flip}}function log(x){state.log.push(x)}
function net(p){return p.cash+(p.house?.sell||0)+(p.married?50000:0)+p.kids*30000+p.pets*15000+p.lifeTiles.length*50000-p.loans}
async function options(title,opts){return new Promise(res=>{modal(title,`<div class="optionGrid">${opts.map(o=>`<button class="option" value="${esc(o.v)}"><h3>${esc(o.t)}</h3><p>${esc(o.d)}</p></button>`).join("")}</div>`,true);document.querySelectorAll(".option[value]").forEach(b=>b.onclick=e=>{e.preventDefault();$("modal").close("picked");res(b.value)});$("modal").addEventListener("close",function h(){ $("modal").removeEventListener("close",h); if($("modal").returnValue==="cancel")res(null);});});}
function modal(t,body,noSubmit=false){$("modalTitle").textContent=t;$("modalBody").innerHTML=body;$("modal").querySelector("menu").classList.toggle("hidden",noSubmit);$("modal").showModal();}
async function changed(){if(mode==="online")await save();render()}async function save(){let {error}=await supabase.from("life_games").update({state,updated_at:new Date().toISOString()}).eq("code",gameCode);if(error)alert(error.message)}
function subscribe(c){stopSync();channel=supabase.channel(`life-${c}`).on("postgres_changes",{event:"UPDATE",schema:"public",table:"life_games",filter:`code=eq.${c}`},p=>receive(p.new.state)).subscribe();poll=setInterval(fetchLatest,1500);fetchLatest()}async function fetchLatest(){if(!gameCode)return;let {data}=await supabase.from("life_games").select("state").eq("code",gameCode).single();if(data?.state)receive(data.state)}function receive(next){let was=state.status==="lobby";state=next;if(was&&state.status==="playing")enter();else render()}function stopSync(){if(channel)supabase.removeChannel(channel);if(poll)clearInterval(poll);channel=null;poll=null}
function cur(){return state.players[state.current]}function viewer(){return mode==="online"?state.players.find(p=>p.id===myId):mode==="local"?cur():state.players.find(p=>p.id===myId)||state.players[0]}function isMyTurn(){return state.status==="playing"&&(mode==="local"||cur()?.id===myId)}function code(){let a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>a[Math.floor(Math.random()*a.length)]).join("")}function id(){return"p_"+Math.random().toString(36).slice(2,10)}function pick(a){return a[Math.floor(Math.random()*a.length)]}function money(n){return "$"+Math.round(n||0).toLocaleString()}function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function toast(txt,type){let d=document.createElement("div");d.className=`toast ${type}`;d.textContent=txt;$("toastLayer").appendChild(d);setTimeout(()=>d.remove(),1250)}
