import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const supabase = createClient(window.LIFE_SUPABASE_URL, window.LIFE_SUPABASE_KEY);

const colors=["#ff6b6b","#4dabf7","#69db7c","#ffd43b","#b197fc","#ff922b"], avatars=["🚗","🚙","🚕","🚐","🏎️","🚘"];
const collegeCareers=[["Doctor",130000,45000],["Lawyer",115000,40000],["Engineer",100000,35000],["Scientist",95000,32000],["Professor",85000,28000],["Pilot",110000,38000]];
const fastCareers=[["Chef",60000,18000],["Artist",55000,16000],["Mechanic",65000,19000],["Influencer",70000,21000],["Entrepreneur",80000,24000],["Designer",72000,22000]];
const homes=[["Cozy Cottage",140000,180000,"🏡"],["City Condo",220000,260000,"🏢"],["Family Home",360000,430000,"🏠"],["Beach House",520000,650000,"🏖️"],["Dream Mansion",800000,1000000,"🏰"]];
const actionCards=[["Win a TV game show",80000,0,0],["Start a charity fundraiser",-20000,1,0],["Car breaks down",-30000,0,0],["Sell an app idea",120000,0,0],["Dream vacation",-40000,1,0],["Settlement",60000,0,0],["Home repairs",-25000,0,0],["Help a friend move",0,1,0],["Stock market jump",100000,0,0],["Night school",-50000,0,20000]];
const petCards=[["Adopt a puppy",-10000,1],["Pet wins show",50000,1],["Pet vet bill",-20000,0],["Adopt a kitten",-10000,1],["Pet sponsorship",40000,1]];
const path=[
{x:35,y:650,type:"start",label:"START",next:[1]},
{x:145,y:650,type:"stop",label:"STOP: PATH",stop:"path"},
{x:260,y:690,type:"college",label:"COLLEGE",branch:"college",next:[3]},
{x:380,y:690,type:"action",label:"ACTION",next:[4]},
{x:500,y:690,type:"payday",label:"PAYDAY",next:[7]},
{x:260,y:585,type:"career",label:"CAREER",branch:"career",next:[6]},
{x:380,y:585,type:"payday",label:"PAYDAY",next:[7]},
{x:500,y:585,type:"stop",label:"STOP: GRAD/JOB",stop:"career",next:[8]},
{x:620,y:585,type:"action",label:"ACTION",next:[9]},
{x:740,y:585,type:"payday",label:"PAYDAY",next:[10]},
{x:860,y:585,type:"stop",label:"STOP: MARRY",stop:"marry",next:[11]},
{x:860,y:470,type:"family",label:"FAMILY",next:[12]},
{x:740,y:470,type:"life",label:"LIFE TILE",next:[13]},
{x:620,y:470,type:"action",label:"ACTION",next:[14]},
{x:500,y:470,type:"stop",label:"STOP: FAMILY PATH",stop:"familyPath"},
{x:380,y:520,type:"family",label:"BABY",branch:"family",next:[16]},
{x:260,y:520,type:"family",label:"TWINS?",next:[19]},
{x:380,y:400,type:"action",label:"ACTION",branch:"free",next:[18]},
{x:260,y:400,type:"payday",label:"PAYDAY",next:[19]},
{x:145,y:460,type:"house",label:"HOUSE",next:[20]},
{x:35,y:460,type:"payday",label:"PAYDAY",next:[21]},
{x:35,y:340,type:"stop",label:"STOP: RISKY",stop:"risk"},
{x:160,y:300,type:"risky",label:"RISKY",branch:"risky",next:[23]},
{x:290,y:300,type:"action",label:"BIG RISK",next:[24]},
{x:420,y:300,type:"tax",label:"TAXES",next:[27]},
{x:160,y:390,type:"payday",label:"SAFE PAYDAY",branch:"safe",next:[26]},
{x:290,y:390,type:"life",label:"LIFE TILE",next:[27]},
{x:540,y:340,type:"career",label:"RAISE",next:[28]},
{x:660,y:340,type:"house",label:"HOUSE",next:[29]},
{x:780,y:340,type:"action",label:"ACTION",next:[30]},
{x:900,y:340,type:"pet",label:"PET",next:[31]},
{x:900,y:215,type:"payday",label:"PAYDAY",next:[32]},
{x:780,y:215,type:"family",label:"FAMILY",next:[33]},
{x:660,y:215,type:"tax",label:"TAXES",next:[34]},
{x:540,y:215,type:"life",label:"LIFE TILE",next:[35]},
{x:420,y:215,type:"action",label:"ACTION",next:[36]},
{x:300,y:215,type:"payday",label:"PAYDAY",next:[37]},
{x:180,y:215,type:"house",label:"HOUSE",next:[38]},
{x:60,y:215,type:"life",label:"LIFE TILE",next:[39]},
{x:60,y:95,type:"retire",label:"RETIRE",stop:"retire",next:[]}
];

let state=fresh(),mode="solo",gameCode=null,myId=null,isHost=false,channel=null,poll=null,tab="career";
const $=id=>document.getElementById(id);
["solo","local","host","join"].forEach(x=>$(x+"Btn").onclick=()=>x==="host"?hostOnline():openLobby(x));
$("backBtn").onclick=showHome;$("lobbyAction").onclick=lobbyAction;$("startBtn").onclick=startGame;$("copyBtn").onclick=()=>navigator.clipboard?.writeText(gameCode||"");$("resetBtn").onclick=()=>location.reload();
$("mainActionBtn").onclick=directorAction;document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTabs();});
function fresh(){return{status:"lobby",players:[],current:0,phase:"choose_path",spin:0,remaining:0,lastCard:null,log:[],winnerId:null};}
function openLobby(kind){mode=kind==="join"?"online":kind;isHost=kind!=="join"&&kind!=="online";gameCode=null;myId=null;state=fresh();$("homeScreen").classList.add("hidden");$("gameScreen").classList.add("hidden");$("lobbyScreen").classList.remove("hidden");$("codeBox").classList.add("hidden");$("joinCode").classList.toggle("hidden",kind!=="join");$("startBtn").classList.add("hidden");$("playersList").innerHTML="";$("statusText").textContent="";$("lobbyAction").classList.remove("hidden");$("playerName").value="";$("lobbyTitle").textContent=kind==="solo"?"Single Player":kind==="local"?"Pass-and-Play Lobby":"Join Online Game";$("lobbyHelp").textContent=kind==="solo"?"Enter your name. Bots join automatically.":kind==="local"?"Add 2–6 players.":"Enter the game code and your name."}
function showHome(){stopSync();$("homeScreen").classList.remove("hidden");$("lobbyScreen").classList.add("hidden");$("gameScreen").classList.add("hidden")}
async function hostOnline(){mode="online";isHost=true;myId=id();gameCode=code();state=fresh();let{error}=await supabase.from("life_games").insert({code:gameCode,state});if(error)return alert(error.message+"\\nRun life-v5-supabase-setup.sql first.");subscribe(gameCode);$("homeScreen").classList.add("hidden");$("lobbyScreen").classList.remove("hidden");$("lobbyTitle").textContent="Host Online Game";$("lobbyHelp").textContent="Share the code. Add yourself, then start.";$("codeBox").classList.remove("hidden");$("codeText").textContent=gameCode;$("joinCode").classList.add("hidden");$("startBtn").classList.remove("hidden")}
async function lobbyAction(){let name=$("playerName").value.trim();if(!name)return alert("Enter a player name.");if(mode==="solo"){state=fresh();addPlayer(name,"human");["Bot Sunny","Bot Sky","Bot Rose"].forEach(n=>addPlayer(n,"bot"));myId=state.players[0].id;return startGame()}if(mode==="local"){if(state.players.length>=6)return alert("Max 6 players.");addPlayer(name,"human");$("playerName").value="";renderLobby();$("startBtn").classList.toggle("hidden",state.players.length<2);return}if(mode==="online"&&!isHost){let c=$("joinCode").value.trim().toUpperCase();let{data,error}=await supabase.from("life_games").select("state").eq("code",c).single();if(error||!data)return alert("Game not found.");state=data.state;gameCode=c;myId=id();if(state.status!=="lobby")return alert("Game already started.");state.players.push(makePlayer(name,"human",state.players.length,myId));await save();subscribe(c);$("codeBox").classList.remove("hidden");$("codeText").textContent=c;$("joinCode").classList.add("hidden");$("lobbyAction").classList.add("hidden");$("statusText").textContent="Joined. Waiting for host.";renderLobby();return}if(mode==="online"&&isHost){if(state.players.some(p=>p.id===myId))return;state.players.push(makePlayer(name,"human",state.players.length,myId));await save();$("playerName").value="";renderLobby()}}
function addPlayer(n,k){state.players.push(makePlayer(n,k,state.players.length))}
function makePlayer(name,kind,i,forced){return{id:forced||id(),name,kind,color:colors[i%colors.length],avatar:avatars[i%avatars.length],pos:0,cash:200000,loans:0,career:null,salary:0,tax:0,home:null,married:false,kids:0,pets:0,lifeTiles:[],path:null,retired:false}}
async function startGame(){if(state.players.length<2)return alert("Add at least 2 players.");state.status="playing";state.phase="choose_path";state.log=["Welcome! First STOP space: choose College or Career."];await changed();enter()}
function enter(){$("homeScreen").classList.add("hidden");$("lobbyScreen").classList.add("hidden");$("gameScreen").classList.remove("hidden");render();setTimeout(botTurn,600)}
function renderLobby(){$("playersList").innerHTML=state.players.map((p,i)=>`<span class="chip"><span class="token" style="background:${p.color}">${esc(p.avatar)}</span>${i+1}. ${esc(p.name)}${p.kind==="bot"?" / Bot":""}</span>`).join("")}
function render(){if(state.status==="lobby")return renderLobby();if(state.status==="playing"||state.status==="ended"){if($("gameScreen").classList.contains("hidden"))enter();renderLeft();renderBoard();renderDirector();renderTabs();renderCard()}}
function car(p){return `${p.avatar}${p.married?"💍":""}${"👶".repeat(Math.min(p.kids,3))}${p.pets?"🐾":""}`}
function renderLeft(){let p=cur(),me=viewer()||p;$("currentPlayerTitle").textContent=p?.name||"—";$("activePlayerCard").innerHTML=`<div class="playerHead"><span class="avatarBig" style="background:${me.color}">${car(me)}</span><div><h2>${esc(me.name)} ${me.retired?"🏁":""}</h2><p class="tiny">${esc(me.career||"No career")} • ${esc(me.home?.name||"No home")}</p></div></div><div class="statGrid"><div class="stat">Cash<br><span class="money">${money(me.cash)}</span></div><div class="stat">Loans<br><span class="debt">${money(me.loans)}</span></div><div class="stat">Family<br>${me.married?"💍":""} 👶${me.kids} 🐾${me.pets}</div><div class="stat">Life<br>⭐ ${me.lifeTiles.length}</div><div class="stat">Salary<br>${money(me.salary)}</div><div class="stat">Net<br><span class="money">${money(net(me))}</span></div></div>`;$("playerStrip").innerHTML=state.players.map((x,i)=>`<div class="miniPlayer ${i===state.current?"current":""}"><span class="token" style="background:${x.color}">${x.avatar}</span><strong>${esc(x.name)}</strong><div class="tiny">${money(net(x))}</div></div>`).join("");$("eventFeed").innerHTML=[...state.log].reverse().slice(0,5).map(x=>`<div class="feedItem">${esc(x)}</div>`).join("")}
function renderBoard(){let b=$("board");b.innerHTML="";path.forEach((t,i)=>{(t.next||[]).forEach(n=>drawRoad(b,t,path[n],(t.next||[]).length>1||t.branch))});path.forEach((t,i)=>{let here=state.players.filter(p=>p.pos===i&&!p.retired);let tokens=here.length?`<div class="tokens">${here.map(p=>`<span class="carToken" style="color:${p.color}" title="${esc(p.name)}">${car(p)}</span>`).join("")}</div>`:"";b.insertAdjacentHTML("beforeend",`<div class="tile ${t.type} ${i===cur()?.pos?"current":""}" style="left:${t.x}px;top:${t.y}px"><strong>${i}</strong><br>${esc(t.label)}${tokens}</div>`)});$("retiredTokens").innerHTML=state.players.filter(p=>p.retired).map(p=>`<span class="carToken" style="color:${p.color}">${car(p)}</span>`).join("")}
function drawRoad(b,a,c,branch){let dx=c.x-a.x,dy=c.y-a.y,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;b.insertAdjacentHTML("beforeend",`<div class="road ${branch?"branch":""}" style="left:${a.x+44}px;top:${a.y+31}px;width:${len}px;transform:rotate(${ang}deg)"></div>`)}
function renderDirector(){let p=cur();$("turnLine").innerHTML=state.status==="ended"?"Game over":`Current turn: <strong>${esc(p?.name||"—")}</strong>`;$("turnBadge").textContent=state.status==="ended"?"Game Over":isMyTurn()?"Your Turn":"Waiting";$("spinnerValue").textContent=state.spin||"?";let title="Waiting",text=`Waiting for ${p?.name}.`,btn="WAIT",disabled=true;if(isMyTurn()&&state.status==="playing"){disabled=false;if(state.phase==="choose_path"){title="STOP: Choose Your Path";text="Choose College for stronger careers and loans, or Career to start earning immediately.";btn="CHOOSE PATH"}else if(state.phase==="spin"){title=`${p.name}'s Turn`;text="Spin the wheel. The game will move your car automatically.";btn="SPIN"}else if(state.phase==="resolve"){title="Resolve Space";text=`You landed on ${path[p.pos].label}. Follow this space's rule.`;btn="RESOLVE"}else if(state.phase==="choice"){title="Choice Required";text="Make the required path or card choice.";btn="CHOOSE"}else if(state.phase==="end"){title="Turn Complete";text="Everything is resolved. End your turn.";btn="END TURN"}else if(state.phase==="retire"){title="Retirement";text="Choose retirement and calculate your final wealth.";btn="RETIRE"}}if(state.status==="ended"){title="Game Over";text="Check the results tab.";btn="RESULTS";disabled=false}$("directorTitle").textContent=title;$("directorText").textContent=text;$("mainActionBtn").textContent=btn;$("mainActionBtn").disabled=disabled}
async function directorAction(){if(state.status==="ended"){tab="results";renderTabs();return}if(!isMyTurn())return;if(state.phase==="choose_path")return choosePath();if(state.phase==="spin")return spin();if(state.phase==="resolve")return resolveCurrent();if(state.phase==="choice")return requiredChoice();if(state.phase==="end")return endTurn();if(state.phase==="retire")return retire()}
async function choosePath(){let ch=await options("Choose Path",[{v:"college",t:"🎓 College",d:"Borrow $100k, draw college career"},{v:"career",t:"💼 Career",d:"Draw career, no college loan"}]);if(!ch)return;let p=cur();p.path=ch;if(ch==="college"){p.loans+=100000;p.cash+=40000;careerFor(p,true);p.pos=2;log(`${p.name} chose College and became ${p.career}.`)}else{careerFor(p,false);p.pos=5;log(`${p.name} chose Career and became ${p.career}.`)}state.phase="spin";await changed()}
async function spin(){let p=cur(),s=1+Math.floor(Math.random()*10);state.spin=s;$("spinner").style.transform=`rotate(${s*360+Math.random()*90}deg)`;log(`${p.name} spun ${s}.`);moveSteps(p,s);state.phase="resolve";await changed()}
function moveSteps(p,steps){for(let i=0;i<steps;i++){let nexts=path[p.pos].next||[];if(!nexts.length)break;p.pos=nexts[0];if(path[p.pos].stop)break}}
async function resolveCurrent(){let p=cur(),t=path[p.pos];if(t.stop==="career")return stopCareer();if(t.stop==="marry"){p.married=true;p.lifeTiles.push("Got Married");lose(p,25000);log(`${p.name} got married at the STOP space.`);state.phase="end"}else if(t.stop==="familyPath"||t.stop==="risk"){state.phase="choice";log(`${p.name} reached a STOP space and must choose a path.`)}else if(t.stop==="retire"){state.phase="retire"}else{applySpace(p,t);state.phase="end"}await changed()}
async function requiredChoice(){let t=path[cur().pos];if(t.stop==="familyPath"){let ch=await options("Choose Your Path",[{v:"family",t:"Family Path",d:"More family spaces and life tiles"},{v:"free",t:"Open Road",d:"More paydays and action spaces"}]);if(!ch)return;cur().pos=ch==="family"?15:17;log(`${cur().name} chose the ${ch==="family"?"Family Path":"Open Road"}.`)}else if(t.stop==="risk"){let ch=await options("Choose Your Route",[{v:"risky",t:"Risky Route",d:"Bigger wins and losses"},{v:"safe",t:"Safe Route",d:"Safer paydays and life tiles"}]);if(!ch)return;cur().pos=ch==="risky"?22:25;log(`${cur().name} chose the ${ch==="risky"?"Risky Route":"Safe Route"}.`)}state.phase="end";await changed()}
function stopCareer(){let p=cur();if(p.path==="college"){careerFor(p,true);log(`${p.name} graduated and confirmed career: ${p.career}.`)}else{log(`${p.name} continued career: ${p.career}.`)}state.phase="end";changed()}
function applySpace(p,t){if(t.type==="payday"){gain(p,p.salary);log(`PAYDAY! ${p.name} collected ${money(p.salary)}.`)}if(t.type==="tax"){lose(p,p.tax);log(`${p.name} paid taxes: ${money(p.tax)}.`)}if(t.type==="career"){p.salary+=20000;gain(p,30000);log(`${p.name} got a raise.`)}if(t.type==="action")drawAction(false);if(t.type==="life"){p.lifeTiles.push("Milestone Memory");gain(p,20000);log(`${p.name} collected a Life Tile.`)}if(t.type==="family")family(p,t.label);if(t.type==="house")houseAuto(p);if(t.type==="pet")pet(p);if(t.type==="risky"){let val=Math.random()>.5?150000:-75000;gain(p,val);log(`${p.name} took a risk: ${val>0?"won":"lost"} ${money(Math.abs(val))}.`)}}
function family(p,label){if(label==="ADOPT PET"){return pet(p)}if(!p.married){p.married=true;p.lifeTiles.push("Got Married");lose(p,25000);log(`${p.name} got married.`)}else{let k=label==="TWINS?"||Math.random()>.75?2:1;p.kids+=k;lose(p,k*15000);for(let i=0;i<k;i++)p.lifeTiles.push("New Baby");log(`${p.name} welcomed ${k} child${k>1?"ren":""}.`)}}
function pet(p){let c=pick(petCards);gain(p,c[1]);p.pets++;if(c[2])p.lifeTiles.push(c[0]);card("Pet Card",c[0],`${money(c[1])}${c[2]?" • Gain Life Tile":""}`);log(`${p.name}: ${c[0]}.`)}
function houseAuto(p){let h=pick(homes);p.cash-=h[1];p.home={name:h[0],price:h[1],sell:h[2],icon:h[3]};card("Home Card",h[0],`Price ${money(h[1])} • Sell ${money(h[2])}`);log(`${p.name} bought ${h[0]}.`);toast("-"+money(h[1]),"loss")}
function drawAction(saveNow=true){let p=cur(),a=pick(actionCards);gain(p,a[1]);if(a[2])p.lifeTiles.push(a[0]);if(a[3])p.salary+=a[3];card("Action Card",a[0],`${a[1]?money(a[1]):""}${a[2]?" • Gain Life Tile":""}${a[3]?" • Raise "+money(a[3]):""}`);log(`${p.name}: ${a[0]}.`);if(saveNow)changed()}
function careerFor(p,college){let c=pick(college?collegeCareers:fastCareers);p.career=c[0];p.salary=c[1];p.tax=c[2];card("Career Card",p.career,`Salary ${money(p.salary)} • Tax ${money(p.tax)}`)}
async function retire(){let p=cur();p.retired=true;if(p.home){gain(p,p.home.sell);log(`${p.name} sold ${p.home.name}.`);p.home=null}let tileCash=p.lifeTiles.length*50000;gain(p,tileCash);log(`${p.name} retired and cashed Life Tiles for ${money(tileCash)}.`);checkEnd();await changed();if(state.status!=="ended")endTurn(true)}
async function endTurn(force=false){if(!force&&!isMyTurn())return;state.spin=0;if(state.players.every(p=>p.retired)){checkEnd();await changed();return}do{state.current=(state.current+1)%state.players.length}while(cur().retired);state.phase=cur().path?"spin":"choose_path";log(`It is now ${cur().name}'s turn.`);await changed();setTimeout(botTurn,700)}
async function botTurn(){if(mode!=="solo"||cur()?.kind!=="bot"||state.status!=="playing")return;setTimeout(async()=>{if(state.phase==="choose_path")await chooseBotPath();else if(state.phase==="spin")await spin();else if(state.phase==="resolve")await resolveCurrent();else if(state.phase==="choice")await botChoice();else if(state.phase==="end")await endTurn(true);else if(state.phase==="retire")await retire()},900)}
async function chooseBotPath(){let p=cur(),college=Math.random()>.45;p.path=college?"college":"career";if(college){p.loans+=100000;p.cash+=40000;careerFor(p,true);p.pos=2}else{careerFor(p,false);p.pos=5}log(`${p.name} chose ${college?"College":"Career"}.`);state.phase="spin";await changed();setTimeout(botTurn,500)}
async function botChoice(){let t=path[cur().pos];if(t.stop==="familyPath")cur().pos=Math.random()>.5?15:17;if(t.stop==="risk")cur().pos=Math.random()>.5?22:25;state.phase="end";await changed();setTimeout(botTurn,500)}
function renderTabs(){let p=viewer()||cur();let html="";if(tab==="career")html=`<div class="infoCard career"><h3>💼 ${esc(p.career||"No career")}</h3><p>Salary: ${money(p.salary)}<br>Tax: ${money(p.tax)}</p></div>`;if(tab==="home")html=`<div class="infoCard house"><h3>${p.home?.icon||"🏠"} ${esc(p.home?.name||"No home")}</h3><p>${p.home?`Bought: ${money(p.home.price)}<br>Sell: ${money(p.home.sell)}`:"Land on a home space to buy."}</p></div>`;if(tab==="life")html=`<h3>⭐ Life Tiles</h3>${(p.lifeTiles.length?p.lifeTiles:["No Life Tiles yet"]).slice(-8).map(x=>`<div class="infoCard life">${esc(x)}</div>`).join("")}`;if(tab==="results")html=[...state.players].sort((a,b)=>net(b)-net(a)).map((x,i)=>`<div class="infoCard"><strong>${i+1}. ${x.avatar} ${esc(x.name)}</strong><br>${money(net(x))}</div>`).join("");$("tabContent").innerHTML=html}
function renderCard(){let c=state.lastCard;$("activeCard").classList.toggle("flipped",!!c?.flip);document.querySelector(".cardFront").innerHTML=c?`<p class="label">${esc(c.type)}</p><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p>`:`<p class="label">Current Card</p><h3>No card yet</h3>`}
function checkEnd(){if(state.players.every(p=>p.retired)){state.status="ended";let w=[...state.players].sort((a,b)=>net(b)-net(a))[0];state.winnerId=w.id;log(`${w.name} wins with ${money(net(w))}!`);tab="results"}}
function gain(p,n){p.cash+=n;if(n>0)toast("+"+money(n),"gain");if(n<0)toast("-"+money(Math.abs(n)),"loss")}function lose(p,n){p.cash-=n;toast("-"+money(n),"loss")}function card(type,title,text){state.lastCard={type,title,text,flip:!state.lastCard?.flip}}function log(x){state.log.push(x)}function net(p){return p.cash+(p.home?.sell||0)+(p.married?50000:0)+p.kids*30000+p.pets*15000+p.lifeTiles.length*50000-p.loans}
async function options(title,opts){return new Promise(res=>{modal(title,`<div class="optionGrid">${opts.map(o=>`<button class="option" value="${esc(o.v)}"><h3>${esc(o.t)}</h3><p>${esc(o.d)}</p></button>`).join("")}</div>`,true);document.querySelectorAll(".option[value]").forEach(b=>b.onclick=e=>{e.preventDefault();$("modal").close("picked");res(b.value)});$("modal").addEventListener("close",function h(){ $("modal").removeEventListener("close",h); if($("modal").returnValue==="cancel")res(null)})})}
function modal(t,body,noSubmit=false){$("modalTitle").textContent=t;$("modalBody").innerHTML=body;$("modal").querySelector("menu").classList.toggle("hidden",noSubmit);$("modal").showModal()}
async function changed(){if(mode==="online")await save();render()}async function save(){let{error}=await supabase.from("life_games").update({state,updated_at:new Date().toISOString()}).eq("code",gameCode);if(error)alert(error.message)}
function subscribe(c){stopSync();channel=supabase.channel(`life-${c}`).on("postgres_changes",{event:"UPDATE",schema:"public",table:"life_games",filter:`code=eq.${c}`},p=>receive(p.new.state)).subscribe();poll=setInterval(fetchLatest,1500);fetchLatest()}async function fetchLatest(){if(!gameCode)return;let{data}=await supabase.from("life_games").select("state").eq("code",gameCode).single();if(data?.state)receive(data.state)}function receive(next){let was=state.status==="lobby";state=next;if(was&&state.status==="playing")enter();else render()}function stopSync(){if(channel)supabase.removeChannel(channel);if(poll)clearInterval(poll);channel=null;poll=null}
function cur(){return state.players[state.current]}function viewer(){return mode==="online"?state.players.find(p=>p.id===myId):mode==="local"?cur():state.players.find(p=>p.id===myId)||state.players[0]}function isMyTurn(){return state.status==="playing"&&(mode==="local"||cur()?.id===myId)}function code(){let a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>a[Math.floor(Math.random()*a.length)]).join("")}function id(){return"p_"+Math.random().toString(36).slice(2,10)}function pick(a){return a[Math.floor(Math.random()*a.length)]}function money(n){return "$"+Math.round(n||0).toLocaleString()}function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function toast(txt,type){let d=document.createElement("div");d.className=`toast ${type}`;d.textContent=txt;$("toastLayer").appendChild(d);setTimeout(()=>d.remove(),1250)}
